name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build project
      run: go build -o dist/ayfetch main.go

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ayfetch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
