name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build project
      run: go build -o dist/ayfetch main.go

    - name: Get the current version
      id: version
      run: echo "VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

    - name: Create Git Tag
      id: tag_creation
      run: |
        TAG="v${{ env.VERSION }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG
        git push origin $TAG
        echo "tag_name=$TAG" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.tag_name }}
        files: dist/ayfetch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
